---
title: "Regression"
author: "Team TBD"
output:
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message= FALSE}
library(tidyverse)
library(forecast)
library(leaps)
library(tidyr)
library(ggplot2)
library(pastecs)
library(gtable)
library(grid)
library(cowplot)
library(GGally)
library(car)
library(AER)
library(leaps)
library(ggpubr)
library(psych)
setwd("C:/xxx/xxx")
engy.df <- read.csv("energy_weather.csv")
engy.t <- as_tibble(engy.df)
```


```{r, message= FALSE}
kv.df <- engy.df[c(2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,20,22,23,26,27,28,29,30,31,32,33)]
options("scipen"=100, "digits"=2)
stat.desc(kv.df, basic = F)

getmode <- function(v){
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

g1 <- getmode(kv.df$generation.biomass)
g2 <- getmode(kv.df$generation.fossil.brown.coal.lignite)
g3 <- getmode(kv.df$generation.fossil.gas)
g4 <- getmode(kv.df$generation.fossil.hard.coal)
g5 <- getmode(kv.df$generation.fossil.oil)
g6 <- getmode(kv.df$generation.hydro.pumped.storage.consumption)
g7 <- getmode(kv.df$generation.hydro.run.of.river.and.poundage)
g8 <- getmode(kv.df$generation.hydro.water.reservoir)
g9 <- getmode(kv.df$generation.nuclear)
g10 <- getmode(kv.df$generation.other)
g11 <- getmode(kv.df$generation.other.renewable)
g12 <- getmode(kv.df$generation.solar)
g13 <- getmode(kv.df$generation.waste)
g14 <- getmode(kv.df$generation.wind.onshore)
hour.mode <- getmode(kv.df$hour)
load.mode <- getmode(kv.df$total.load.actual)
price.mode <- getmode(kv.df$price.actual)
temp.mode <- getmode(kv.df$temp)
pressure.mode <- getmode(kv.df$pressure)
humidity.mode <- getmode(kv.df$humidity)
wind_speed.mode <- getmode(kv.df$wind_speed)
wind_deg.mode <- getmode(kv.df$wind_deg)
rain_1h.mode <- getmode(kv.df$rain_1h)
rain_3h.mode <- getmode(kv.df$rain_3h)
snow_3h.mode <- getmode(kv.df$snow_3h)
clouds_all.mode <- getmode(kv.df$clouds_all)
```

```{r, message= FALSE}
p1 <- ggplot(kv.df, aes(hour,total.load.actual)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2)  + theme_bw() + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +  theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + scale_x_discrete(name = "") + scale_y_continuous(name = "Total Load Actual") + theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
p2 <- ggplot(kv.df, aes(hour,price.actual)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2)  + theme_bw() + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +  theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + scale_x_discrete(name = "Hour") + scale_y_continuous(name = "Price Actual")+scale_x_discrete(breaks=c("00:00:00+00:00","01:00:00+00:00","02:00:00+00:00","03:00:00+00:00","04:00:00+00:00","05:00:00+00:00","06:00:00+00:00","07:00:00+00:00","08:00:00+00:00","09:00:00+00:00","10:00:00+00:00","11:00:00+00:00","12:00:00+00:00","13:00:00+00:00","14:00:00+00:00","15:00:00+00:00","16:00:00+00:00","17:00:00+00:00","18:00:00+00:00","19:00:00+00:00","20:00:00+00:00","21:00:00+00:00","22:00:00+00:00","23:00:00+00:00"),
        labels=c("0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23"))
g1 <- ggplotGrob(p1)
g2 <- ggplotGrob(p2)
g <- rbind(g1, g2, size="first")
g$widths <- unit.pmax(g1$widths, g2$widths) 
g$layout[grepl("guide", g$layout$name),c("t","b")] <- c(1,nrow(g))
grid.newpage()
grid.draw(g)
```


```{r, message= FALSE}
temp <- ggplot(kv.df, aes(y=temp)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "Temprature in Kelvin") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

pres <- ggplot(kv.df, aes(y=pressure)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "Pressure in hPa") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

hmdy <- ggplot(kv.df, aes(y=humidity)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "Humidity in %") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

wind_s <- ggplot(kv.df, aes(y=wind_speed)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "Wind Speed in m/s") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

wind_d <- ggplot(kv.df, aes(y=wind_deg)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "Wind Direction") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

rain_1 <- ggplot(kv.df, aes(y=rain_1h)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "Rain in Past 1 Hour in mm") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

rain_3 <- ggplot(kv.df, aes(y=rain_3h)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "Rain in Past 3 Hours in mm") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

snow_3 <- ggplot(kv.df, aes(y=snow_3h)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "Snow in Past 3 Hours in mm") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

cloud <- ggplot(kv.df, aes(y=clouds_all)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "Cloud Cover in %") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

plot_grid(temp, pres, hmdy, wind_s, wind_d, rain_1, rain_3, snow_3, cloud, labels = "")
```

```{r, message= FALSE}
names(kv.df) <- c("hour","g.biomass","g.fosill.brown.coal","g.fossil.gas","g.fossil.hard.coal","g.fossil.oil","g.hydro.pumped","g.hydro.run","g.hydro.reservoir","g.nuclear","g.other","g.renewable","g.solar","g.waste","g.wind.onshore","load","price","tmp","prs","hmd","w_speed","w_direction","rain_1","rain_3","snow_3","clouds%")

g1 <- ggplot(kv.df, aes(y=g.biomass)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "g.biomass") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

g2 <- ggplot(kv.df, aes(y=g.fosill.brown.coal)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "g.fosill.brown.coal") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

g3 <- ggplot(kv.df, aes(y=g.fossil.gas)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "g.fossil.gas") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

g4 <- ggplot(kv.df, aes(y=g.fossil.hard.coal)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "g.fossil.hard.coal") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

g5 <- ggplot(kv.df, aes(y=g.fossil.oil)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "g.fossil.oil") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

g6 <- ggplot(kv.df, aes(y=g.hydro.pumped)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "g.hydro.pumped") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

g7 <- ggplot(kv.df, aes(y=g.hydro.run)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "g.hydro.run-of-river") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

g8 <- ggplot(kv.df, aes(y=g.hydro.reservoir)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "g.hydro.reservoir") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

g9 <- ggplot(kv.df, aes(y=g.nuclear)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "g.nuclear") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

g10 <- ggplot(kv.df, aes(y=g.other)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "g.other") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

g11 <- ggplot(kv.df, aes(y=g.renewable)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "g.renewable") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

g12 <- ggplot(kv.df, aes(y=g.solar)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "g.solar") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

g13 <- ggplot(kv.df, aes(y=g.waste)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "g.waste") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

g14 <- ggplot(kv.df, aes(y=g.wind.onshore)) + geom_boxplot() + stat_boxplot(geom = "errorbar", width = 0.2) + scale_y_continuous(name = "g.wind.onshore") + coord_flip() + theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank()) 

plot_grid(g1,g2,g3,g4,g5,g6,g7,g8,g9,g10,g11,g12,g13,g14, labels = "")
```

```{r, message= FALSE}
try <- engy.df[,-c(1,2,17,18,19,21,24,25,35)]
try <- try[-c(25172,25126,25165,29316,836,835,887,833,837,832,834,830,831,838,829,839,812,2026,816,861,29963,856,826,813,815,863,16654,30883,875,25572,26155,836,25128,25172,25126,873,883,879,854,886,515,889,1966,811,511,810,9992,877,512,9993),]
names(try) <- c("g1","g2","g3","g4","g5","g6","g7","g8","g9","g10","g11","g12","g13","g14","LOAD","PRICE","tmp","prs","hmd","w_s","w_d","r_1","r_3","s_3","cld","t1","t2")
ggcorr(try, method = c("everything", "pearson"),low = "seagreen", mid = "white", high = "rosybrown")
```

```{r, message= FALSE}
set.seed(1)
train.index <- sample(nrow(try),round(nrow(try))*0.8)
train <- try[train.index,]
valid <- try[-train.index,]
load.lm <- lm(LOAD ~., data = train)
load.lm.step.both <- step(load.lm, direction = "both")
summary(load.lm.step.both)
load.lm.step.pred <- predict(load.lm.step.both,data = valid)
accuracy(load.lm.step.both$fitted.values, train$LOAD)
accuracy(load.lm.step.pred, valid$LOAD)
vif(load.lm)
```


```{r, message= FALSE}
load.lm <- lm(LOAD ~., data = train)
load.lm.step.for <- step(load.lm, direction = "forward")
summary(load.lm.step.for)
load.lm.step.pred <- predict(load.lm.step.for,data = valid)
accuracy(load.lm.step.for$fitted.values, train$LOAD)
accuracy(load.lm.step.pred,valid$LOAD)
vif(load.lm)
```


```{r, message= FALSE}
exhaust <- regsubsets(LOAD ~., data = train, nbest =1, nvmax = 23, method = "exhaustive")
summary(exhaust)
```


```{r, message = FALSE}
s1 <- ggplot(try, aes(y= LOAD, x=g1))+geom_point()+geom_smooth()+ theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s2 <- ggplot(try, aes(y= LOAD, x=g2))+geom_point()+geom_smooth()+ theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s3 <- ggplot(try, aes(y= LOAD, x=g3))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s4 <- ggplot(try, aes(y= LOAD, x=g4))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s5 <- ggplot(try, aes(y= LOAD, x=g5))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s6 <- ggplot(try, aes(y= LOAD, x=g6))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s7 <- ggplot(try, aes(y= LOAD, x=g7))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s8 <- ggplot(try, aes(y= LOAD, x=g8))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s9 <- ggplot(try, aes(y= LOAD, x=g9))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s11 <- ggplot(try, aes(y= LOAD, x=g11))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s12 <- ggplot(try, aes(y= LOAD, x=g12))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s13 <- ggplot(try, aes(y= LOAD, x=g13))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s14 <- ggplot(try, aes(y= LOAD, x=g14))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s15 <- ggplot(try, aes(y= LOAD, x=tmp))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s16 <- ggplot(try, aes(y= LOAD, x=prs))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s17 <- ggplot(try, aes(y= LOAD, x=hmd))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s18 <- ggplot(try, aes(y= LOAD, x=w_s))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s19 <- ggplot(try, aes(y= LOAD, x=w_d))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s20 <- ggplot(try, aes(y= LOAD, x=s_3))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())


ggarrange(s1,s2,s3,s4,s5,s6,s7,s8,s9,s11,s12,s13,s14,s15,s16,s17,s18,s19,s20,ncol=4,nrow=5)

```


```{r, message = FALSE}
s1 <- ggplot(try, aes(y= PRICE, x=g1))+geom_point()+geom_smooth()+ theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s2 <- ggplot(try, aes(y= PRICE, x=g2))+geom_point()+geom_smooth()+ theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s3 <- ggplot(try, aes(y= PRICE, x=g3))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s4 <- ggplot(try, aes(y= PRICE, x=g4))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s5 <- ggplot(try, aes(y= PRICE, x=g5))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s6 <- ggplot(try, aes(y= LOAD, x=g6))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s7 <- ggplot(try, aes(y= PRICE, x=g7))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s8 <- ggplot(try, aes(y= PRICE, x=g8))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s9 <- ggplot(try, aes(y= PRICE, x=g9))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s11 <- ggplot(try, aes(y= PRICE, x=g11))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s12 <- ggplot(try, aes(y= PRICE, x=g12))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s13 <- ggplot(try, aes(y= PRICE, x=g13))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s14 <- ggplot(try, aes(y= PRICE, x=g14))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s15 <- ggplot(try, aes(y= PRICE, x=tmp))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s16 <- ggplot(try, aes(y= PRICE, x=prs))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s17 <- ggplot(try, aes(y= PRICE, x=hmd))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s18 <- ggplot(try, aes(y= PRICE, x=w_s))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s19 <- ggplot(try, aes(y= PRICE, x=w_d))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())

s20 <- ggplot(try, aes(y= PRICE, x=s_3))+geom_point()+geom_smooth()+ 
theme_bw() + theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) + theme(axis.title.y=element_blank(), axis.text.y=element_blank(), axis.ticks.y=element_blank())


ggarrange(s1,s2,s3,s4,s5,s6,s7,s8,s9,s11,s12,s13,s14,s15,s16,s17,s18,s19,s20,ncol=4,nrow=5)

```


```{r, message= FALSE}
load.mdl <- lm(LOAD ~ .-PRICE -g10 -r_1 -r_3 -cld -t1, data = train)
vif(load.mdl)
summary(load.mdl)
load.mdl.pred <- predict(load.mdl, valid)
accuracy(load.mdl$fitted.values, train$LOAD)
accuracy(load.mdl.pred, valid$LOAD)
par(mfrow=c(2,2))
plot(load.mdl)
```


```{r, message= FALSE}
qqnorm(load.mdl$residuals, pch = 1, frame = FALSE)
qqline(load.mdl$residuals, col = "pink", lwd = 2)
```


```{r, message= FALSE}
ggplot(load.mdl,aes(x=load.mdl$residuals)) +theme_bw()+ geom_histogram(aes(y=..density..),alpha=.4) + geom_density(color="pink2",size=1.3)+
  stat_function(fun = dnorm,alpha=0.8,lwd=0.6, args = list(mean = mean(load.mdl$residuals), sd = sd(load.mdl$residuals)))+labs(x= "Residuals",y="",title = "Histogram of Regression Residuals")+  theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) 
```

```{r, message= FALSE}
load.ip <- lm(LOAD ~ .-PRICE -g10 -r_1 -r_3 -cld -t1 +I(g8^2) +I(g3^2) +I(g6^2), data = train)
load.ip.pred <- predict(load.ip, valid)
summary(load.ip)
vif(load.ip)

accuracy(load.ip$fitted.values, train$LOAD)
accuracy(load.ip.pred, valid$LOAD)

par(mfrow=c(2,2))
plot(load.ip)

ggplot(load.ip,aes(x=load.ip$residuals)) +theme_bw()+ geom_histogram(aes(y=..density..),alpha=.4) + geom_density(color="pink2",size=1.3)+
  stat_function(fun = dnorm,alpha=0.8,lwd=0.6, args = list(mean = mean(load.ip$residuals), sd = sd(load.mdl$residuals)))+labs(x= "Residuals",y="",title = "Histogram of Regression Residuals")+  theme(panel.border=element_blank(),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.line=element_line(color="black")) 
```
